## uses JSON path
topics: &id1
    - Small Business
    - Business
    - Entrepreneurship
    - Lean Startup
    - Agile Methods
    - Visual Communication
    - Small Business
    - Entrepreneur
    - Design Thinking
    - Customer Development
    - Marketing Strategy
    - Visual Thinking
    - Marketing
    - Networking
    - Finance
    - MBA
    - Strategy
    - Sales
countries: &id2
    - gb
cities: &id3
    - london
    - manchester
api_scrapers:
    EventBrite:
        Events: &eventbrite
            model: Event
            endpoint: https:..www.eventbrite.com.json.event_search.
            request:
                format: Querystring
                 fields:
                        app_key: MWY0YWRmMjNhZjFl
                        country: GB
                        keywords:
                            type: csv
                            values: *id1
            response:
                format: json
                item_graph: [$..event]
                fields:
                    title: title
                    description: description
                    location: [$.venue.name,$.venue.address,$.venue.address_2,$.venue.city,$.venue.postal_code]
                    start_date: start_date
                    url: url
                    people: Unknown
                    notes: Unknown
                    source: EventBrite
                    Organiser_id: [$.organiser.id]
            pager:
                request:
                    per_page:
                        name: max
                        amount: 100
                    page: page
                response:
                    total_results: total_items
                    page_results: num_showing
        Organiser: &eventbrite
            model: Organiser
            response:
                format: json
                item_graph: [$..organiser]
                fields:
                    telephone: Organiser[$.telephone]
                    email: Organiser[$.email]
            fields:
                app_key: MWY0YWRmMjNhZjFl
                id:
            pager:
                request:
                    per_page:
                        name: max
                        amount: 100
                    page: page
                response:
                    total_results: total_items
                    page_results: num_showing
    Meetup:
        endpoint: http:..api.meetup.com.2.events.json.
        request_format: Querystring
        response:
            format: json
            event_graph: [$..results]
            fields:
                title: name
                description: description
                location: [$.venue.name,$.venue.address_1,$.venue.address_2,$.venue.address_3,$.venue.city,$.venue.zip]
                start_date: start_date
                url: event_url
                telephone: Unknown
                email: Unknown
                people: Unknown
                notes: Unknown
                source: Meetup
        fields:
            key: 601b6869351a5d69521e40232f4a1a65
            country: gb
            topic:
                type: one_per_request
                values: *id1
        pager:
            request:
                per_page:
                    name: page
                    amount: 100
                page: offset
            response:
                total_results: total_count
                page_results: count