topics: &id1
    - Small Business
    - Business
    - Entrepreneurship
    - Lean Startup
    - Agile Methods
    - Visual Communication
    - Small Business
    - Entrepreneur
    - Design Thinking
    - Customer Development
    - Marketing Strategy
    - Visual Thinking
    - Marketing
    - Networking
    - Finance
    - MBA
    - Strategy
    - Sales
countries: &id2
    - gb
cities: &id3
    - london
    - manchester
log4r_config:
  # define all pre config ... none
  # pre_config:
  # define all loggers ...
  loggers:
    - name      : grater_log
      additive  : 'false'
      trace     : 'false'      
      outputters:
        - stderr
#         - logfile 
#         - email    

  # define all outputters (incl. formatters)      
  outputters: []
    # - type     : StderrOutputter
    #   name     : stderr 
    #   only_at  :
    #     - WARN
    #     - Error
    #     - FATAL
    # - type     : StdoutOutputter
    #   name     : debug

# Format:
#   APIName
#     Endpoints
#         endpoint
#           request
#               type
#               fields
#           response
#               [RailsModel|APIName/Endpoint  -  either a rails model to create with scraped fields, or another endpoint request to spawn, which will be passed any containing entities
#                   item_path                 -  path to select all items
#                   fields                    -  fields within each item
#               , ///]
#           pager
#             request
#             response
