FindNetworkingEvents:
    GreaterLondonEvents:
        #should run before other scrapers:
        root: true
        request:
            format: Http
            endpoint: http://www.findnetworkingevents.com/events/index.cfm?action=eventslist&region=1
            fields: {}
        response:
            type: XpathHtml
        scrapers:
            FnEventDetails:
                item_path: //*[@summary="Results"]
                fields:
                    no_key: .//*[@class='quoteTxt']/a[1]/@href
    FnEventDetails:
        request:
            endpoint: http://www.findnetworkingevents.com/
            format: Querystring
            fields: {}
        response:
            type: XpathHtml
            vos:
                Event:
                    item_path: id('rightContent')
                    fields:
                        title: ./p[1]
                        description: (id('rightContent')/p[contains(.,'Details')])[1]
                        start_date: ./p[2]
                        location: .//p[@class="quoteTxt"]
                        cost: .//*[@class="quoteMid"]/following-sibling::p[1]
                        target_audience: UNKNOWN
                        notes: .//*[@class="quoteMid"]/following-sibling::p[2]
                        url: ENDPOINT
                        telephone: UNKNOWN
                        email: UNKNOWN
                        people: UNKNOWN
                    related_to:
                        Organiser:
                            item_query: //*[@id='rightContent']
                            fields:
                                name:
                                url: (id('rightContent')/p[contains(.,'Details')])[last()]